responses = {
    "hello": "Hi there!",
    "hi": "Hello!",
    "how are you": "I'm a bot, so I don't have feelings, but I'm here to chat!",
    "what is your name": "I'm Chatbot! Nice to meet you.",
    "bye": "Goodbye! Have a great day!",
    "tell me a joke": "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "what time is it": "I can't check the time, but you can!",
    "who are you": "I'm a chatbot created to chat with you!",
    "thank you": "You're welcome!",
    "good morning": "Good morning! Hope you have a great day!",
    "good night": "Good night! Sleep well!",
    "what's the weather": "I don't have access to weather data, but you can check online!",
    "what is 2+2": "2 + 2 = 4",
    "can you help me": "Of course! What do you need help with?",
    "what is the capital of france": "The capital of France is Paris.",
    "who is the president of the usa": "You can check online for the current president!",
    "tell me a fun fact": "Did you know honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3000 years old and still perfectly good to eat!",
    "what's your favorite color": "I like all colors equally!",
    "do you like music": "I don't have ears, but I think music is great!",
    "what do you do": "I chat with people and try to be helpful!",
    "who invented the lightbulb": "Thomas Edison is credited with inventing the lightbulb, but many others contributed to its development!",
    "how far is the moon": "The Moon is about 384,400 km away from Earth.",
    "tell me a quote": "'The only way to do great work is to love what you do.' - Steve Jobs",
    "who wrote harry potter": "J.K. Rowling is the author of the Harry Potter series.",
    "what is the tallest mountain": "Mount Everest is the tallest mountain in the world, standing at 8,848 meters (29,029 feet).",
    "what is the speed of light": "The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).",
    "how many continents are there": "There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
    "what is pi": "Pi is approximately 3.14159 and is the ratio of a circle's circumference to its diameter.",
    "what is the meaning of life": "The meaning of life is a philosophical question. Some say it's 42!",
    "what's your favorite movie": "I don't watch movies, but I hear Inception is great!",
    "how do airplanes fly": "Airplanes fly using the principles of lift, thrust, drag, and weight!",
    "who painted the mona lisa": "The Mona Lisa was painted by Leonardo da Vinci.",
    "what is the pythagorean theorem": "The Pythagorean Theorem states that a² + b² = c² in a right triangle.",
    "what is gravity": "Gravity is the force that attracts objects with mass.",
    "how does photosynthesis work": "Plants convert sunlight into energy using chlorophyll.",
    "what is python": "Python is a popular programming language.",
    "who invented the internet": "Tim Berners-Lee is often credited with inventing the World Wide Web.",
    "what is a black hole": "A black hole is a region in space with gravitational pull so strong that not even light can escape.",
    "what is dna": "DNA carries genetic instructions for living organisms.",
    "how do rockets work": "Rockets work by expelling exhaust gases to produce thrust.",
    "capital of japan": "Tokyo is the capital of Japan.",
    "where is the eiffel tower": "The Eiffel Tower is in Paris, France.",
    "currency of india": "The currency of India is the Indian Rupee (INR).",
    "tallest building in the world": "The Burj Khalifa in Dubai is the tallest building.",
    "best place to visit in italy": "Rome, Venice, and Florence are popular destinations.",
    "who is taylor swift": "Taylor Swift is a famous singer-songwriter.",
    "director of inception": "Christopher Nolan directed Inception.",
    "lead actor in mission impossible": "Tom Cruise stars in Mission Impossible.",
    "when was minecraft released": "Minecraft was released in 2011.",
    "who plays thor": "Chris Hemsworth plays Thor in the Marvel movies.",
    "riddle: i speak without a mouth": "An echo!",
    "what has keys but can't open locks": "A piano!",
    "what gets wetter as it dries": "A towel!",
    "riddle: what comes once in a minute": "The letter 'M'!",
    "how to reduce stress": "Exercise, meditation, and good sleep help reduce stress.",
    "how to study effectively": "Use active recall and spaced repetition for better retention.",
    "how to make coffee": "Brew ground coffee beans with hot water.",
    "how to tie a tie": "Loop the wide end around the narrow end and pull through.",
    "gawa ni?": "Bins",
    "default": "Sorry, I didn't understand that. I am limited to certain responses since I'm a rule-based chatbot."
}
